#!/usr/bin/env bash
#
# tpm2-tss/mayhem/build.sh — build a representative subset of tpm2-tss's auto-generated
# System-API (SAPI) fuzz harnesses as sanitized libFuzzer targets (+ standalone reproducers),
# AND tpm2-tss's own marshaling cmocka unit tests for mayhem/test.sh.
#
# FUZZED SURFACE: tpm2-tss's TPM2 marshaling / unmarshaling code. Each harness is generated by
# script/gen_fuzz.py from include/tss2/tss2_sys.h:
#   *_Prepare harnesses — drive Tss2_Sys_<Cmd>_Prepare(): the fuzz bytes fill the command
#                         PARAMETER structs (via fuzz_fill) which are then MARSHALED into the
#                         command buffer (the marshal path).
#   *_Complete harnesses — drive Tss2_Sys_<Cmd>_Complete(): the fuzz bytes become the raw TPM
#                          RESPONSE buffer (fed through the fuzzing TCTI) which is then
#                          UNMARSHALED into the output structs (the unmarshal path — historically
#                          the bug-rich surface: bounds checks on attacker-controlled response sizes).
# The fuzzing TCTI (test/fuzz/tcti/) replaces a real TPM: no hardware/network needed.
#
# Build contract comes from the org base ENV (CC/CXX/SANITIZER_FLAGS/LIB_FUZZING_ENGINE/SRC/
# STANDALONE_FUZZ_MAIN). The tpm2-tss libraries are compiled WITH $SANITIZER_FLAGS (via configure's
# CFLAGS) so the marshal/unmarshal code itself — not just the harness — is instrumented.
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# `=` (not `:=`) for SANITIZER_FLAGS so an explicit empty --build-arg builds with NO sanitizers.
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer -g}"
# DEBUG_FLAGS: force DWARF-3 symbols on every fuzz/standalone compile. clang-19 defaults to DWARF-5;
# Mayhem's triage requires DWARF < 4 (§6.2 item 10). Placed AFTER $SANITIZER_FLAGS so it overrides
# any -gdwarf-N the sanitizer flags might imply.
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${STANDALONE_FUZZ_MAIN:=/opt/mayhem/StandaloneFuzzTargetMain.c}"
: "${MAYHEM_JOBS:=$(nproc)}"
: "${OUT:=/mayhem}"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX LIB_FUZZING_ENGINE STANDALONE_FUZZ_MAIN MAYHEM_JOBS OUT

cd "$SRC"

# Representative subset of the 219 auto-generated SAPI fuzz targets. Chosen to cover both the
# marshal (_Prepare) and unmarshal (_Complete) paths across structurally diverse TPM2 commands:
#   GetCapability  — variable-length TPMS_CAPABILITY_DATA union unmarshal (classic overflow surface)
#   Create         — nested TPM2B_PUBLIC / TPM2B_PRIVATE / TPMT_PUBLIC
#   Load           — TPM2B_PRIVATE + TPM2B_PUBLIC marshal, TPM2B_NAME unmarshal
#   NV_Read        — variable-length TPM2B_MAX_NV_BUFFER unmarshal
#   ReadPublic     — TPMT_PUBLIC / TPM2B_NAME unmarshal
#   Unseal         — TPM2B_SENSITIVE_DATA unmarshal
FUZZERS=(
  Tss2_Sys_GetCapability_Prepare
  Tss2_Sys_GetCapability_Complete
  Tss2_Sys_Create_Prepare
  Tss2_Sys_Create_Complete
  Tss2_Sys_Load_Complete
  Tss2_Sys_NV_Read_Complete
  Tss2_Sys_ReadPublic_Complete
  Tss2_Sys_Unseal_Complete
)

# Coverage build needs -fsanitize=fuzzer-no-link on the instrumented library objects so the
# fuzzer can collect edge coverage; the final harness link supplies the engine itself.
SAN_LIB="$SANITIZER_FLAGS -fsanitize=fuzzer-no-link"

export GEN_FUZZ=1   # required by configure.ac to enable fuzz-target generation
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"

# ── 1) bootstrap + configure (SYS-only build: no TPM device/sim, no FAPI/policy) ───────────────────
./bootstrap

# Configure the project. CFLAGS carry the sanitizer + fuzzer-no-link so the tss2 libraries
# (mu/sys/util) and the fuzzing TCTI are instrumented. --with-fuzzing=ossfuzz wires
# $LIB_FUZZING_ENGINE into the .fuzz link line (FUZZ_LDFLAGS / FUZZ_CPPFLAGS).
./configure \
  CC="$CC" \
  CXX="$CXX" \
  CFLAGS="$SAN_LIB $DEBUG_FLAGS" \
  CXXFLAGS="$SAN_LIB $DEBUG_FLAGS" \
  --enable-debug \
  --with-fuzzing=ossfuzz \
  --enable-tcti-fuzzing \
  --disable-tcti-device \
  --disable-tcti-mssim \
  --disable-tcti-swtpm \
  --disable-tcti-spi-ftdi \
  --disable-tcti-spi-lt2go \
  --disable-doxygen-doc \
  --disable-shared \
  --disable-fapi \
  --disable-policy

# OSS-Fuzz comments out the doxygen DX rules that break the non-doc make.
sed -i 's/@DX_RULES@/# @DX_RULES@/g' Makefile

# ── 2) Build the instrumented tss2 static archives + the fuzzing TCTI, and GENERATE the per-target
#       harness sources (script/gen_fuzz.py writes test/fuzz/<Cmd>.fuzz.c, each defining test_invoke).
#       We do NOT use `make fuzz-targets`: its generated main (test/fuzz/main-sys.c) builds the SYS
#       context via Tss2_TctiLdr_Initialize(getenv TPM20TEST_TCTI), but with --disable-shared +
#       --disable-tcti-* the no-dlopen loader's TCTI registry is EMPTY, so it can never find the
#       "fuzzing" TCTI — every input fails at setup and nothing is actually fuzzed. We link our own
#       driver (mayhem/harnesses/mayhem-main-sys.c) that instantiates the fuzzing TCTI DIRECTLY. ─────
mkdir -p "$OUT"

# Build the static .a archives (produced as a side effect of the .la library targets) by building
# one .fuzz target through make — that resolves all the libtss2 + fuzzing-TCTI dependencies once.
# FUZZ_LDFLAGS override avoids the hardcoded -lFuzzingEngine link (we don't link the stock main).
make -j"$MAYHEM_JOBS" FUZZ_LDFLAGS="$LIB_FUZZING_ENGINE" "test/fuzz/${FUZZERS[0]}.fuzz"

# Regenerate the per-target sources (the build above already created them, but be explicit).
python3 script/gen_fuzz.py

# Static archives the manual link needs (instrumented with the sanitizer build above).
LIBS=(
  "$SRC/src/tss2-sys/.libs/libtss2-sys.a"
  "$SRC/src/tss2-mu/.libs/libtss2-mu.a"
  "$SRC/src/tss2-rc/.libs/libtss2-rc.a"
  "$SRC/test/fuzz/tcti/.libs/libtss2-tcti-fuzzing.a"
  "$SRC/.libs/libutil.a"
)
for a in "${LIBS[@]}"; do
  [ -f "$a" ] || { echo "ERROR: expected static archive missing: $a" >&2; exit 1; }
done

INC=(-I"$SRC/include" -I"$SRC/include/tss2" -I"$SRC/src" -I"$SRC/src/tss2-sys"
     -I"$SRC/src/tss2-tcti" -I"$SRC/test/fuzz" -I"$SRC/test/integration" -I"$SRC")
DRIVER="$SRC/mayhem/harnesses/mayhem-main-sys.c"

# Standalone run-once main object (no libFuzzer runtime) for the -standalone reproducers.
STANDALONE_OBJ="$SRC/mayhem-standalone-main.o"
$CC $SANITIZER_FLAGS $DEBUG_FLAGS -c "$STANDALONE_FUZZ_MAIN" -o "$STANDALONE_OBJ"

# ── 3) Link each harness twice: libFuzzer target (-> /mayhem/<name>) + standalone reproducer. ───────
for f in "${FUZZERS[@]}"; do
  gen="$SRC/test/fuzz/$f.fuzz.c"
  [ -f "$gen" ] || { echo "ERROR: generated harness $gen missing" >&2; exit 1; }

  # libFuzzer target
  $CC $SANITIZER_FLAGS $DEBUG_FLAGS "${INC[@]}" \
      "$DRIVER" "$gen" "${LIBS[@]}" $LIB_FUZZING_ENGINE -lcrypto -ldl \
      -o "$OUT/$f"

  # standalone reproducer (run-once main, no fuzzing engine)
  $CC $SANITIZER_FLAGS $DEBUG_FLAGS "${INC[@]}" \
      "$DRIVER" "$gen" "${LIBS[@]}" "$STANDALONE_OBJ" -lcrypto -ldl \
      -o "$OUT/$f-standalone"

  echo "built $f (+ standalone)"
done

# ── 4) Build tpm2-tss's OWN marshaling cmocka unit tests with NORMAL flags (separate tree) so
#       mayhem/test.sh only RUNS them. These are self-contained (no TPM/network) and exercise the
#       exact (un)marshal code the fuzzers hit. ──────────────────────────────────────────────────────
TESTDIR="$SRC/mayhem-tests"
rm -rf "$TESTDIR"; mkdir -p "$TESTDIR"
# The fuzz binaries are already saved to $OUT, so we can free the in-tree autotools config
# (config.status) — a VPATH build refuses while the srcdir is still configured.
make distclean >/dev/null 2>&1 || true
# distclean removes Makefile-fuzz-generated.am (it's in DISTCLEANFILES), but Makefile.am
# unconditionally `include`s it, so automake during the VPATH configure needs it back.
# Regenerate it (the script writes the generated .am + the per-target .fuzz.c files).
python3 script/gen_fuzz.py
# Configure a clean VPATH tree with normal flags (no sanitizers, so test.sh is an honest oracle and
# the cmocka harnesses don't trip ASan on their deliberate boundary pokes). No fuzzing here.
( cd "$TESTDIR" && \
  "$SRC/configure" \
    CC="$CC" CXX="$CXX" \
    --disable-tcti-device \
    --disable-tcti-mssim \
    --disable-tcti-swtpm \
    --disable-tcti-spi-ftdi \
    --disable-tcti-spi-lt2go \
    --disable-doxygen-doc \
    --disable-fapi \
    --disable-policy \
    --enable-unit )
( cd "$TESTDIR" && sed -i 's/@DX_RULES@/# @DX_RULES@/g' Makefile )

# Build only the marshaling unit-test binaries (self-contained, cmocka, no TPM).
MARSHAL_TESTS=(
  test/unit/UINT8-marshal
  test/unit/UINT16-marshal
  test/unit/UINT32-marshal
  test/unit/UINT64-marshal
  test/unit/TPMA-marshal
  test/unit/TPM2B-marshal
  test/unit/TPMS-marshal
  test/unit/TPML-marshal
  test/unit/TPMT-marshal
  test/unit/TPMU-marshal
)
( cd "$TESTDIR" && make -j"$MAYHEM_JOBS" "${MARSHAL_TESTS[@]}" ) \
  && echo "built tpm2-tss marshaling unit tests in mayhem-tests/" \
  || echo "WARNING: marshaling unit tests failed to build (mayhem/test.sh will report)" >&2

echo "build.sh complete:"
for f in "${FUZZERS[@]}"; do ls -la "$OUT/$f" "$OUT/$f-standalone" 2>&1 || true; done
